import Base
import ./LAWS.bend as Laws

def Laws.vote_goal_is_five():
  {==}

def Laws.engineer_needs_three_brains():
  {==}

def Laws.swamp_has_six_brains():
  {==}

def Laws.grass_is_walkable():
  {==}

def Laws.water_is_blocked():
  {==}

def Laws.tree_is_blocked():
  {==}

def Laws.brain_is_walkable():
  {==}

def Laws.warp_is_walkable():
  {==}

def Laws.elder_is_npc():
  {==}

def Laws.throne_is_interact():
  {==}
